In [1]:
import sys
print(sys.executable)

c:\Users\Admin\AppData\Local\Programs\Python\Python312\python.exe


# **Giai đoạn 1: Nền tảng cơ bản**

### 1.Tensor là gì và tại sao cần học về tensor: ###
- Tensor là cấu trúc dữ liệu cơ bản trong PyTorch, tương tự như NumPy array nhưng được tối ưu cho deep learning
- Tensor có thể chạy trên GPU để tăng tốc độ tính toán
- Tensor tự động tính được đạo hàm (gradient) - rất quan trọng trong quá trình huấn luyện neural network

### 2.Các cách tạo tensor cơ bản: ###

In [2]:
import torch
import numpy as np

# Tạo tensor từ list
x = torch.tensor([1, 2, 3, 4])

# Tạo tensor với giá trị ngẫu nhiên
random_tensor = torch.rand(size=(3, 4))
print(random_tensor)

# Tạo tensor toàn số 0 hoặc 1
zeros = torch.zeros(size=(3, 4))
ones = torch.ones(size=(3, 4))
eye = torch.eye(3)
print(zeros)
print(ones)
print(eye)

# Tạo tensor với giá trị tuần tự
range_tensor = torch.arange(start=0, end=10, step=2)
linspace_tensor = torch.linspace(start=0.1, end=1, steps=10)
print(range_tensor)
print(linspace_tensor)

# Tạo tensor với shape giống tensor khác
x_ones = torch.ones_like(x)
x_zeros = torch.zeros_like(x)
print(x_ones)
print(x_zeros)


tensor([[0.1175, 0.8600, 0.8945, 0.3270],
        [0.3809, 0.9897, 0.5415, 0.7454],
        [0.7958, 0.9694, 0.5060, 0.0181]])
tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])
tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])
tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])
tensor([0, 2, 4, 6, 8])
tensor([0.1000, 0.2000, 0.3000, 0.4000, 0.5000, 0.6000, 0.7000, 0.8000, 0.9000,
        1.0000])
tensor([1, 1, 1, 1])
tensor([0, 0, 0, 0])


### 3.Các thuộc tính quan trọng của tensor: ###
- shape: kích thước của tensor
- dtype: kiểu dữ liệu (float32, int64,...)
- device: tensor được lưu ở đâu (CPU hay GPU)

In [4]:
# Ví dụ kiểm tra thuộc tính
print(x.shape)      # Kích thước
print(x.dtype)      # Kiểu dữ liệu
print(x.device)     # Thiết bị lưu tensor

torch.Size([4])
torch.int64
cpu


### 4.Các phép toán tensor cơ bản: ###

In [9]:
tensor = torch.tensor([[1, 2], [3, 4], [5, 6], [7, 8], [9, 10]])

tensor1 = torch.tensor([[1, 2], [3, 4]])
tensor2 = torch.tensor([[5, 6], [7, 8]])

new_shape = (2, 5)

# Phép cộng
result = tensor1 + tensor2
# hoặc
result = torch.add(tensor1, tensor2)

# Phép nhân ma trận
result = torch.matmul(tensor1, tensor2)
# hoặc
result = tensor1 @ tensor2

# Reshape tensor
reshaped = tensor.reshape(new_shape)
# hoặc
reshaped = tensor.view(new_shape)

print(reshaped)

tensor([[ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10]])


### 5.Các thao tác tensor nâng cao: ###

In [21]:
# Indexing
print(tensor[0])          # Phần tử đầu tiên
print(tensor[1:4])       # Slice tensor
print(tensor[4])        # Phần tử thứ 5

# Concatenate tensors
concat = torch.cat([tensor1, tensor2], dim=0)
print(concat)

# Stack tensors
stacked = torch.stack([tensor1, tensor2], dim=0)
print(stacked)

tensor([1, 2])
tensor([[3, 4],
        [5, 6],
        [7, 8]])
tensor([ 9, 10])
tensor([[1, 2],
        [3, 4],
        [5, 6],
        [7, 8]])
tensor([[[1, 2],
         [3, 4]],

        [[5, 6],
         [7, 8]]])


### 6.Chuyển đổi giữa các kiểu dữ liệu: ###

In [ ]:
# Chuyển từ NumPy sang PyTorch
numpy_array = np.array([1, 2, 3])
torch_tensor = torch.from_numpy(numpy_array)

# Chuyển từ PyTorch sang NumPy
numpy_array = torch_tensor.numpy()